namespace: masterlittle
name: google
version: 1.0.1
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
description: null
license_file: COPYING
tags: [cloud, google, security, secrets]
repository: https://github.com/masterlittle/ansible_google-secret-manager
homepage: https://github.com/masterlittle/ansible_google-secret-manager
build_ignore:
  - 'venv/'